language: node_js
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
env:
  - ENABLE_IDENTITY=false ENABLE_IDENTITY_LOGIN=false BUNGIE_API_KEY=4405d43938494aefb9e6c8c09e9a146f SITE_URL=https://backup.destinyclanwarfare.com DISALLOW_ROBOTS=true ENABLE_MATCH_HISTORY=true ENABLE_PREVIOUS_LEADERBOARDS=true
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn deploy
notifications:
  email:
    on_success: never
