language: node_js
sudo: false
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn deploy
