[build.environment]
  YARN_VERSION = "1.12.3"
  RUBY_VERSION = "2.6.2"
  GO_VERSION = "1.12"

[context.deploy-preview.environment]
  BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  SITE_URL = "https://beta.destinyclanwarfare.com"
  DISALLOW_ROBOTS = "true"
  ENABLE_MATCH_HISTORY = "true"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"
  ENABLE_ADVERTS = "false"
  ENABLE_PROXY_URLS = "true"

[context.branch-deploy.environment]
  BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  SITE_URL = "https://beta.destinyclanwarfare.com"
  DISALLOW_ROBOTS = "true"
  ENABLE_MATCH_HISTORY = "true"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"
  ENABLE_ADVERTS = "false"
  ENABLE_PROXY_URLS = "true"

[context.production.environment]
  BUNGIE_API_KEY = "e44a1c455b634479aa069be92838857d"
  SITE_URL = "https://destinyclanwarfare.com"
  DISALLOW_ROBOTS = "false"
  ENABLE_MATCH_HISTORY = "true"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"
  ENABLE_ADVERTS = "false"
  ENABLE_PROXY_URLS = "true"
