[context.deploy-preview.environment]
  GATSBY_ENABLE_IDENTITY = "false"
  GATSBY_ENABLE_IDENTITY_LOGIN = "false"
  GATSBY_BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  GATSBY_SITE_URL = "https://beta.destinyclanwarfare.com"
  GATSBY_DISALLOW_ROBOTS = "true"
  GATSBY_ENABLE_MATCH_HISTORY = "true"
  GATSBY_ENABLE_PREVIOUS_LEADERBOARDS = "true"

[context.branch-deploy.environment]
  GATSBY_ENABLE_IDENTITY = "true"
  GATSBY_ENABLE_IDENTITY_LOGIN = "true"
  GATSBY_BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  GATSBY_SITE_URL = "https://beta.destinyclanwarfare.com"
  GATSBY_DISALLOW_ROBOTS = "true"
  GATSBY_ENABLE_MATCH_HISTORY = "true"
  GATSBY_ENABLE_PREVIOUS_LEADERBOARDS = "true"

[context.production.environment]
  GATSBY_ENABLE_IDENTITY = "false"
  GATSBY_ENABLE_IDENTITY_LOGIN = "false"
  GATSBY_BUNGIE_API_KEY = "e44a1c455b634479aa069be92838857d"
  GATSBY_SITE_URL = "https://destinyclanwarfare.com"
  GATSBY_DISALLOW_ROBOTS = "false"
  GATSBY_ENABLE_MATCH_HISTORY = "false"
  GATSBY_ENABLE_PREVIOUS_LEADERBOARDS = "true"
