[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Content-Security-Policy = "default-src 'self'; style-src 'self' bungie.net *.bungie.net; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self';"

[dev]
  command = "yarn start:next"
  port = 9000
  targetPort = 9001
  # [dev.https]
  #   certFile = "ssl/cert.pem"
  #   keyFile = "ssl/key.pem"
