[context.deploy-preview.environment]
  ENABLE_IDENTITY = "false"
  ENABLE_IDENTITY_LOGIN = "false"
  BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  SITE_URL = "https://beta.destinyclanwarfare.com"
  DISALLOW_ROBOTS = "true"
  ENABLE_MATCH_HISTORY = "false"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"

[context.branch-deploy.environment]
  ENABLE_IDENTITY = "false"
  ENABLE_IDENTITY_LOGIN = "false"
  BUNGIE_API_KEY = "a426c047234646c4ac8ebe9394260bd7"
  SITE_URL = "https://beta.destinyclanwarfare.com"
  DISALLOW_ROBOTS = "true"
  ENABLE_MATCH_HISTORY = "false"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"

[context.production.environment]
  ENABLE_IDENTITY = "false"
  ENABLE_IDENTITY_LOGIN = "false"
  BUNGIE_API_KEY = "e44a1c455b634479aa069be92838857d"
  SITE_URL = "https://destinyclanwarfare.com"
  DISALLOW_ROBOTS = "false"
  ENABLE_MATCH_HISTORY = "false"
  ENABLE_PREVIOUS_LEADERBOARDS = "true"
