version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5
  cypress: cypress-io/cypress@3.1.4
  newhighsco: newhighsco/orb@1.9.0

parameters:
  workflow:
    type: string
    default: test_and_release
  cache-version:
    type: string
    default: v2
  cypress-cache-folder:
    type: string
    default: CYPRESS_CACHE_FOLDER="./node_modules/CypressBinary"
  install-command:
    type: string
    default: << pipeline.parameters.cypress-cache-folder >> yarn install --frozen-lockfile

jobs:
  cypress:
    executor:
      name: cypress/default
      node-version: 18.18.0
    steps:
      - attach_workspace:
          at: .
      - cypress/run-tests:
          cypress-command: << pipeline.parameters.cypress-cache-folder >> yarn cypress run --config baseUrl=https://deploy-preview-$CIRCLE_PR_NUMBER.next.destinyclanwarfare.com

workflows:
  version: 2
  test_and_release:
    when:
      equal: [test_and_release, << pipeline.parameters.workflow >>]
    jobs:
      - newhighsco/setup:
          name: setup
          cache-version: << pipeline.parameters.cache-version >>
          install-command: << pipeline.parameters.install-command >>
      - newhighsco/test:
          name: test
          post-steps:
            - codecov/upload
          requires:
            - setup
      - newhighsco/build:
          name: build
          command: yarn build:storybook
          path-to-persist: storybook
          requires:
            - test
      - newhighsco/snapshot:
          name: snapshot
          requires:
            - build
      - newhighsco/release:
          name: release
          requires:
            - snapshot
          filters:
            branches:
              only:
                - main
  e2e:
    when:
      equal: [e2e, << pipeline.parameters.workflow >>]
    jobs:
      - newhighsco/setup:
          name: setup
          cache-version: << pipeline.parameters.cache-version >>
          install-command: << pipeline.parameters.install-command >>
      - cypress:
          requires:
            - setup
