version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:8.15.0-jessie
    steps:
      - checkout
      - run:
          command: yarn test
