version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10.14.1
    working_directory: ~/repo
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn test
      - codecov/upload
workflows:
  version: 2
  build:
    jobs:
      - build
